name: 'DEMO: 3. Package Final ZIP'

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The release tag to download the MSI from (e.g., v1.0.0-demo)'
        required: true
        type: string

jobs:
  package_zip:
    runs-on: windows-2022

    steps:
      - name: 'Download signed file from GitHub Release'
        run: gh release download ${{ github.event.inputs.release_tag }} --pattern "*.msi" --dir .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Create a fake Version.txt in correct path'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "Sources/GUI/Installer/bin" | Out-Null
          Set-Content -Path "Sources/GUI/Installer/bin/Version.txt" -Value "${{ github.event.inputs.release_tag }}"

      - name: 'Create and name final ZIP package'
        id: package_info
        shell: pwsh
        run: |
          $msi_file = "DisplayControlSoftware for ZRCT-300.msi"
          $version_txt = "Sources/GUI/Installer/bin/Version.txt"
          $zip_name = "DCS_Setup_${{ github.event.inputs.release_tag }}.zip"
          Compress-Archive -Path $msi_file, $version_txt -DestinationPath $zip_name -Force
          echo "zip_name=$zip_name" >> $env:GITHUB_OUTPUT

      - name: 'Upload final ZIP package'
        uses: actions/upload-artifact@v4
        with:
          name: DCS_Setup_${{ github.event.inputs.release_tag }}
          path: ${{ steps.package_info.outputs.zip_name }}
